version: '2'
services:
  db:
    image: postgres:9.6.3-alpine
    ports:
      - "5432:5432"

  api:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ".:/app"
